# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74d20f016a7ee43c608121b55c68903df9312799c40f52d70b54da41205624b572cbdb9116b79f11aaf4360c31ed5bb3bd7735e8a1987ae6e6dbde129c8b6f41

test:
  secret_key_base: deb78d1762a550db5bf2c603ae4e3f452b6863b823efea68f6c839eba2cf1121e7d9f93a931d74f87a336c058b25b63ddc9903921a69faa1ed67c9f5dd86e5cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
