# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdd5b8060c189dc7a910b6059f8ae4fc330a287b303d06019b0c995475b677528887c2eb7165bf4c9229d45169ead00cb71ed5635e56d97c32135d7422a2187

test:
  secret_key_base: 23de9ea405b0aafd8b9fe73de82621f61b6c99a7c1df897566f68a240a088f1d9108ba85a5ca7f81dfa97a004e6fde8722dd3801f8970268dcdf7bff9434d3d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
